#!/bin/bash

# ANSI color codes and formatting
BOLD='\033[1m'
DIM='\033[2m'
ITALIC='\033[3m'
UNDERLINE='\033[4m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Function to print centered text with a specified color
print_centered() {
    local color=$1
    local text=$2
    local width=$(tput cols)
    local padding=$(( (width - ${#text}) / 2 ))
    printf "%${padding}s" ""
    echo -e "${color}${text}${NC}"
}

# Function to print a horizontal line
print_line() {
    local width=$(tput cols)
    printf '%*s\n' "${width}" '' | tr ' ' '─'
}

# Function to print status with icon
print_status() {
    local status=$1
    local message=$2
    if [ "$status" -eq 0 ]; then
        echo -e "${GREEN}✓${NC} ${message}"
    else
        echo -e "${RED}✗${NC} ${message}"
    fi
}

clear
print_line
print_centered "${BLUE}${BOLD}" "AdvBox Configuration Script"
print_centered "${CYAN}${DIM}" "Version 1.0.0 - Setup started at $(date '+%Y-%m-%d %H:%M:%S')"
print_centered "${MAGENTA}${ITALIC}" "by AnmiTaliDev"
print_line
echo

# Compiler selection
echo -e "${YELLOW}${BOLD}Compiler Selection:${NC}"
echo -e "${DIM}─────────────────${NC}"

# Check available C compilers
declare -A c_compilers
if command -v clang >/dev/null 2>&1; then
    c_compilers["clang"]=$(clang --version | head -n1)
fi
if command -v gcc >/dev/null 2>&1; then
    c_compilers["gcc"]=$(gcc --version | head -n1)
fi

# Display available C compilers
echo -e "${WHITE}Available C compilers:${NC}"
i=1
declare -A c_compiler_map
for compiler in "${!c_compilers[@]}"; do
    echo -e "$i) ${CYAN}${compiler}${NC} - ${DIM}${c_compilers[$compiler]}${NC}"
    c_compiler_map[$i]=$compiler
    ((i++))
done

# Get C compiler choice
echo
read -p "Select C compiler (default: clang): " c_choice
c_choice=${c_choice:-1}
if [[ ! ${c_compiler_map[$c_choice]} ]]; then
    echo -e "${RED}Invalid choice. Using default.${NC}"
    c_choice=1
fi
selected_cc=${c_compiler_map[$c_choice]}
echo -e "${GREEN}Selected C compiler: ${WHITE}${selected_cc}${NC}"

# Check available C++ compilers
declare -A cxx_compilers
if command -v clang++ >/dev/null 2>&1; then
    cxx_compilers["clang++"]=$(clang++ --version | head -n1)
fi
if command -v g++ >/dev/null 2>&1; then
    cxx_compilers["g++"]=$(g++ --version | head -n1)
fi

# Display available C++ compilers
echo
echo -e "${WHITE}Available C++ compilers:${NC}"
i=1
declare -A cxx_compiler_map
for compiler in "${!cxx_compilers[@]}"; do
    echo -e "$i) ${CYAN}${compiler}${NC} - ${DIM}${cxx_compilers[$compiler]}${NC}"
    cxx_compiler_map[$i]=$compiler
    ((i++))
done

# Get C++ compiler choice
echo
read -p "Select C++ compiler (default: clang++): " cxx_choice
cxx_choice=${cxx_choice:-1}
if [[ ! ${cxx_compiler_map[$cxx_choice]} ]]; then
    echo -e "${RED}Invalid choice. Using default.${NC}"
    cxx_choice=1
fi
selected_cxx=${cxx_compiler_map[$cxx_choice]}
echo -e "${GREEN}Selected C++ compiler: ${WHITE}${selected_cxx}${NC}"

# Create build configuration
echo
echo -e "${YELLOW}${BOLD}Creating build configuration:${NC}"
echo -e "${DIM}──────────────────────────${NC}"

# Generate build_config.mk
cat > build_config.mk << EOF
# Generated by configure.sh at $(date '+%Y-%m-%d %H:%M:%S')
CC = ${selected_cc}
CXX = ${selected_cxx}
EOF

print_status 0 "Created build configuration"

# Generate Makefile from template
echo
echo -e "${YELLOW}${BOLD}Generating Makefile:${NC}"
echo -e "${DIM}─────────────────${NC}"

if [ -f "makefile.in" ]; then
    sed -e "s/@CURRENT_YEAR@/$(date +%Y)/" \
        -e "s/@CURRENT_USER@/$(whoami)/" \
        -e "s/@CURRENT_DATE@/$(date '+%Y-%m-%d %H:%M:%S')/" \
        makefile.in > Makefile
    print_status 0 "Generated ${WHITE}Makefile${NC} from template"
else
    print_status 1 "${WHITE}makefile.in${NC} template not found"
    exit 1
fi

# Create directories
echo
echo -e "${YELLOW}${BOLD}Creating directories:${NC}"
echo -e "${DIM}───────────────────${NC}"

directories=("bin" "build" "lib")
for dir in "${directories[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        print_status 0 "Created ${WHITE}${dir}/${NC} directory"
    else
        echo -e "${CYAN}ℹ${NC} Directory ${WHITE}${dir}/${NC} already exists"
    fi
done

# Configuration summary
echo
print_line
print_centered "${GREEN}${BOLD}" "Configuration Completed Successfully!"
echo
echo -e "${CYAN}${BOLD}Next steps:${NC}"
echo -e "  1. Run ${WHITE}make${NC} to build all targets"
echo -e "  2. Run ${WHITE}make install${NC} to install programs (may require sudo)"
echo -e "  3. Run ${WHITE}make clean${NC} to remove build files"
print_line

exit 0